project_name: mcp-client

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: mcp
    main: ./cmd/mcp
    binary: mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/security-mcp/mcp-client/internal/cli.Version={{.Version}}
      - -X github.com/security-mcp/mcp-client/internal/cli.GitCommit={{.Commit}}
      - -X github.com/security-mcp/mcp-client/internal/cli.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: mcp
    name_template: "mcp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/*.md
      - docs/*.yaml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: security-mcp
    name: mcp-client
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## mcp-client {{ .Tag }}

    Release of mcp-client {{ .Tag }}.

    ### Installation

    Download the appropriate binary for your platform below.
  footer: |
    **Full Changelog**: https://github.com/security-mcp/mcp-client/compare/{{ .PreviousTag }}...{{ .Tag }}
